"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { formatCurrency, formatNumber } from "@/lib/utils";

type Band = { id: string; botId: string; baseSymbol: string; status: string; allocatedQuoteAmount: number; availableQuoteAmount: number; retainedBaseAmount: number; lowPrice: number; highPrice: number; levelCount: number };
type Portfolio = { id: string; mode: string; autoLive: boolean; freeQuoteAmount: number; bands: Band[] };
type Comparison = { endingEquityUsd: number; endingCashUsd: number; closedCycles: number; retainedBaseByAsset: Record<string, number> };

export function PortfolioConsole() {
  const [portfolios, setPortfolios] = useState<Portfolio[]>([]); const [total, setTotal] = useState(3000); const [base, setBase] = useState(1000); const [comparison, setComparison] = useState<{ fixed: Comparison; adaptive: Comparison } | null>(null); const [coverage, setCoverage] = useState<{ from: string; to: string } | null>(null); const [assumptions, setAssumptions] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const [replayArtifact, setReplayArtifact] = useState<string | null>(null);
  function downloadReplay() { if (!replayArtifact) return; const url = URL.createObjectURL(new Blob([replayArtifact], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "portfolio-replay-inputs-results.json"; link.click(); URL.revokeObjectURL(url); }
  async function load() { const response = await fetch("/api/portfolios"); if (!response.ok) throw new Error("Unable to load portfolios."); const body = await response.json(); setPortfolios(body.portfolios ?? []); }
  useEffect(() => { const refresh = () => void load().catch((error) => setMessage(error instanceof Error ? error.message : "Unable to load portfolios.")); refresh(); const timer = setInterval(refresh, 30000); return () => clearInterval(timer); }, []);
  async function create() { setBusy(true); setMessage(null); try { const response = await fetch("/api/portfolios", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ totalCapitalUsd: total, baseAllocationUsd: base }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to create paper portfolio."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create paper portfolio."); } finally { setBusy(false); } }
  async function compare() { setBusy(true); setMessage(null); try { const response = await fetch("/api/portfolios/replay", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ totalCapitalUsd: total, baseAllocationUsd: base, days: 14 }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to run comparison."); setReplayArtifact(JSON.stringify(body, null, 2)); setComparison(body.comparison); setAssumptions(body.assumptions ?? []); setCoverage(body.coverage ?? null); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to run comparison."); } finally { setBusy(false); } }
  return <div className="space-y-5">
    <div className="border border-[var(--line)] bg-[var(--panel-soft)] p-4"><div className="font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--muted)]">Paper only</div><div className="mt-2 text-sm text-[var(--muted)]">BTC accumulation and SOL quote accumulation share a tracked cash pool. This screen has no live controls.</div><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="text-xs text-[var(--muted)]">Total capital<input className="mt-1 w-full border border-[var(--line)] bg-[var(--bg)] px-3 py-2 text-sm text-white" type="number" min="200" value={total} onChange={(e) => setTotal(Number(e.target.value))} /></label><label className="text-xs text-[var(--muted)]">Allocation per asset (BTC = SOL)<input className="mt-1 w-full border border-[var(--line)] bg-[var(--bg)] px-3 py-2 text-sm text-white" type="number" min="100" value={base} onChange={(e) => setBase(Number(e.target.value))} /></label><div className="flex items-end gap-2"><button disabled={busy || total < base * 2} onClick={() => void create()} className="h-10 border border-[var(--accent-line)] bg-[var(--accent-soft)] px-3 font-mono text-[10px] uppercase tracking-[0.12em] text-[var(--accent)] disabled:opacity-45">Create paper</button><button disabled={busy} onClick={() => void compare()} className="h-10 border border-[var(--line)] px-3 font-mono text-[10px] uppercase tracking-[0.12em] text-[var(--muted)] disabled:opacity-45">Compare 14d</button></div></div>{message ? <div className="mt-3 text-sm text-[var(--red)]">{message}</div> : null}</div>
    {portfolios.map((portfolio) => <div key={portfolio.id} className="border border-[var(--line)] bg-[var(--panel)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] px-4 py-3"><div><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-[var(--muted)]">{portfolio.mode} portfolio</div><div className="mt-1 text-sm font-medium text-white">Cash pool {formatCurrency(portfolio.freeQuoteAmount)}</div></div><span className="border border-[var(--line)] px-2 py-1 font-mono text-[10px] uppercase text-[var(--muted)]">paper</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-[var(--muted)]"><tr><th className="px-4 py-3">Asset</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Allocated</th><th className="px-4 py-3">Cash</th><th className="px-4 py-3">Accumulated</th><th className="px-4 py-3">Range</th><th className="px-4 py-3"></th></tr></thead><tbody>{portfolio.bands.map((band) => <tr key={band.id} className="border-t border-[var(--line)]"><td className="px-4 py-3 font-medium text-white">{band.baseSymbol}</td><td className="px-4 py-3 text-[var(--muted)]">{band.status}</td><td className="px-4 py-3 text-white">{formatCurrency(band.allocatedQuoteAmount)}</td><td className="px-4 py-3 text-white">{formatCurrency(band.availableQuoteAmount)}</td><td className="px-4 py-3 text-[var(--accent)]">{formatNumber(band.retainedBaseAmount, 8)} {band.baseSymbol}</td><td className="px-4 py-3 text-[var(--muted)]">{formatNumber(band.lowPrice, 2)} → {formatNumber(band.highPrice, 2)} · {band.levelCount} levels</td><td className="px-4 py-3"><Link className="text-[var(--accent)] hover:text-white" href={`/bots/${band.botId}`}>Open bot</Link></td></tr>)}</tbody></table></div></div>)}
    {comparison ? <div className="border border-[var(--line)] bg-[var(--panel-soft)] p-4"><div className="font-mono text-[10px] uppercase tracking-[0.16em] text-[var(--muted)]">Historical comparison</div><button onClick={downloadReplay} className="mt-2 text-xs text-[var(--accent)]">Download inputs and results</button><table className="mt-3 w-full text-left text-sm"><thead className="text-xs text-[var(--muted)]"><tr><th className="py-2">Scenario</th><th className="py-2">Ending equity</th><th className="py-2">Ending cash</th><th className="py-2">Closed cycles</th><th className="py-2">Retained base</th></tr></thead><tbody>{(["fixed", "adaptive"] as const).map((key) => <tr key={key} className="border-t border-[var(--line)]"><td className="py-2 text-white">{key}</td><td className="py-2 text-white">{formatCurrency(comparison[key].endingEquityUsd)}</td><td className="py-2 text-white">{formatCurrency(comparison[key].endingCashUsd)}</td><td className="py-2 text-white">{comparison[key].closedCycles}</td><td className="py-2 text-[var(--accent)]">{Object.entries(comparison[key].retainedBaseByAsset).map(([asset, amount]) => `${asset} ${formatNumber(amount, 8)}`).join(" · ") || "—"}</td></tr>)}</tbody></table>{coverage ? <div className="mt-3 text-xs text-[var(--muted)]">Coverage: {coverage.from} → {coverage.to}</div> : null}<div className="mt-3 text-xs text-[var(--muted)]">Simulated historical comparison; these figures are not investment returns or a recommendation.</div>{assumptions.length ? <ul className="mt-2 list-disc pl-5 text-xs text-[var(--muted)]">{assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}</ul> : null}</div> : null}
  </div>;
}
